### ISSUE TITLE
Problem while configuring mlx-models

### ISSUE THREAD

**Issue by AtakanTekparmak** [LucasSte/MLX-vs-Pytorch#1]
While following the installation manual, trying to run `./configure.sh` inside `mlx_models`, I receive the following error, I have `git-lfs` installed:
```bash
(venv) atakantekparmak@Atakans-MacBook-Pro mlx_models % ./configure.sh      
/Users/atakantekparmak/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models/tmp
~/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models/tmp ~/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models
~/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models/tmp/mlx-examples ~/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models/tmp ~/Desktop/personal/trials/benchmark-mlx/MLX-vs-pytorch/mlx_models
HEAD is now at 09aaeac fix moe conversion (#802)
[INFO] Loading
Traceback (most recent call last):
  File "/Users/atakantekparmak/Desktop/personal/trials/benchmark-mlx/MLX-vs-Pytorch/mlx_models/tmp/mlx-examples/llms/llama/convert.py", line 219, in <module>
    weights, params = globals()[args.model_name](torch_path, dtype=args.dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atakantekparmak/Desktop/personal/trials/benchmark-mlx/MLX-vs-Pytorch/mlx_models/tmp/mlx-examples/llms/llama/convert.py", line 74, in tiny_llama
    model = transformers.AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atakantekparmak/Desktop/personal/trials/benchmark-mlx/MLX-vs-Pytorch/venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atakantekparmak/Desktop/personal/trials/benchmark-mlx/MLX-vs-Pytorch/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3456, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by LucasSte** [comment]
When you were running `./configure.sh` for the `pytorch_models` folder, did you have a connection interruption? The download of the TinyLLama in the PyTorch folder might be corrupted.

Can you delete the `TinyLlama-1.1B-Chat-v1.0` folder from `pytorch_models` and run both `./configure.sh` scripts again?

**Comment by AtakanTekparmak** [comment]
Honestly that might be the case, I did a fresh pull and install and it seems to work, closing the issue 👍
